name: EXPOSE YOUR REPO S3CR3T5
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose
        run: |
          git clone https://${{ secrets.PAT }}@github.com/arbaz-diwan/demo-repo.git
          cd demo-repo
          git checkout main
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name ${{ secrets.USER_USERNAME }}
          git config --local user.Password ${{ secrets.USER_PASSWORD }}
          cat << EOF > demo-file.txt
          "EMAIL:" ${{ secrets.USER_EMAIL }}
          EOF              
          git add .
          git commit -m "exposed secrets"
          git push origin main -f
