name: EXPOSE YOUR REPO S3CR3T5
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose
        run: |
          cat << EOF > demo-file.txt
          "EMAIL:" ${{ secrets.USER_EMAIL }}
          EOF              
          cat demo-file.txt
